### ISSUE TITLE
Ubuntu 22.04.2 LTS + SublimeText 4

### ISSUE THREAD

**Issue by dannycoin** [raphaelquintao/QColor#7]
You need to follow these steps:

1 ) **pip install pywebview[qt]**
_ref:_ https://pywebview.flowrl.com/guide/installation.html#dependencies

2 ) **nano ~/.config/sublime-text/Packages/QColor/lib/picker.py**
_at the end of the code search and replace:
this: **window.closing += on_closing**
for this: **window.events.closing += on_closing**_

enjoy!

**Comment by raphaelquintao** [comment]
Thanks, i will make a update as soon as possible.
